version: "3"

services:
  django:
    build: .
    container_name: django
    command: python manage.py runserver 5.61.35.86:8080
    volumes:
    - .:/usr/src/app/
    ports:
    - 8080:8080
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=5.61.35.86 0.0.0.0 localhost 127.0.0.1
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
  celery:
    build: .
    command: celery -A fbk_gos worker -l info
    volumes:
      - .:/usr/src/app/
    depends_on:
      - django
      - redis
  celery-beat:
    build: .
    command: celery -A fbk_gos beat -l info
    volumes:
      - .:/usr/src/app/
    depends_on:
      - django
      - redis
  redis:
    image: "redis:alpine"
    ports:
    - 6379:6379
