# Generated by Django 3.1.7 on 2021-03-17 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Название')),
                ('inn', models.IntegerField(db_index=True, verbose_name='ИНН')),
                ('ogrn', models.IntegerField(db_index=True, verbose_name='ОГРН')),
                ('customer_id', models.IntegerField(verbose_name='ID в госзакупках')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Название')),
                ('inn', models.IntegerField(db_index=True, verbose_name='ИНН')),
                ('ogrn', models.IntegerField(db_index=True, verbose_name='ОГРН')),
                ('customer_id', models.IntegerField(verbose_name='ID в госзакупках')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Наименование закупки')),
                ('status', models.CharField(max_length=255, verbose_name='Статус')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Сумма закупки')),
                ('date_published', models.DateField(blank=True, verbose_name='Дата размещения')),
                ('date_signature', models.DateField(blank=True, verbose_name='Дата заключения')),
                ('date_start', models.DateField(blank=True, verbose_name='Начало исполнения')),
                ('date_end', models.DateField(blank=True, verbose_name='Конец испоолнения')),
                ('contract_reestr_number', models.PositiveBigIntegerField(db_index=True, verbose_name='Реестровый номер')),
                ('contract_number', models.CharField(max_length=15, verbose_name='Номер контракта')),
                ('files_order', models.TextField(blank=True, verbose_name='Файлы закупки')),
                ('files_contract', models.TextField(blank=True, verbose_name='Файлы контракта')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zakupki.client')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zakupki.customer')),
            ],
        ),
    ]
