# Generated by Django 3.1.7 on 2021-03-17 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakupki', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='customer_id',
            new_name='client_id',
        ),
        migrations.AddField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активный'),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активный'),
        ),
        migrations.AddField(
            model_name='customer',
            name='orders',
            field=models.IntegerField(blank=True, default=0, verbose_name='Закупок'),
        ),
        migrations.AddField(
            model_name='order',
            name='keywords',
            field=models.TextField(blank=True, verbose_name='Поиск по ключевым словам'),
        ),
    ]
