# Generated by Django 3.1.7 on 2021-03-17 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakupki', '0002_auto_20210317_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='inn',
            field=models.IntegerField(db_index=True, unique=True, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='client',
            name='ogrn',
            field=models.IntegerField(db_index=True, unique=True, verbose_name='ОГРН'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.IntegerField(blank=True, unique=True, verbose_name='ID в госзакупках'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='inn',
            field=models.IntegerField(db_index=True, unique=True, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='ogrn',
            field=models.IntegerField(blank=True, db_index=True, unique=True, verbose_name='ОГРН'),
        ),
    ]
