# Generated by Django 3.1.7 on 2021-03-20 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zakupki', '0003_auto_20210317_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='number',
            field=models.PositiveBigIntegerField(blank=True, db_index=True, null=True, verbose_name='Номер закупки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Сумма закупки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zakupki.client'),
        ),
        migrations.AlterField(
            model_name='order',
            name='contract_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Номер контракта'),
        ),
        migrations.AlterField(
            model_name='order',
            name='contract_reestr_number',
            field=models.PositiveBigIntegerField(blank=True, db_index=True, null=True, verbose_name='Реестровый номер'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_end',
            field=models.DateField(blank=True, null=True, verbose_name='Конец исполнения'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_published',
            field=models.DateField(blank=True, null=True, verbose_name='Дата размещения'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_signature',
            field=models.DateField(blank=True, null=True, verbose_name='Дата заключения'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_start',
            field=models.DateField(blank=True, null=True, verbose_name='Начало исполнения'),
        ),
        migrations.AlterField(
            model_name='order',
            name='files_contract',
            field=models.TextField(blank=True, null=True, verbose_name='Файлы контракта'),
        ),
        migrations.AlterField(
            model_name='order',
            name='files_order',
            field=models.TextField(blank=True, null=True, verbose_name='Файлы закупки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='keywords',
            field=models.TextField(blank=True, null=True, verbose_name='Поиск по ключевым словам'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='title',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Наименование закупки'),
        ),
    ]
