# Generated by Django 3.1.7 on 2021-03-30 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakupki', '0005_auto_20210325_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='contract_reestr_number',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Реестровый номер'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ikz',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ИКЗ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='reg_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True, verbose_name='Номер закупки'),
        ),
    ]
