# Generated by Django 3.1.7 on 2021-03-30 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakupki', '0007_auto_20210330_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='contract_status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Статус контракта'),
        ),
    ]
