# Generated by Django 3.1.7 on 2021-03-30 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakupki', '0008_order_contract_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='parser_status',
            field=models.IntegerField(default=0, verbose_name='Уровень парсинга'),
        ),
    ]
